### PR TITLE
Fix helicsInputGetComplexVector

### LINKED ISSUE #32: helicsInputGetComplexVector(), unknown comlexpVector
Error is being thrown in line 2433 of HELICS/src/api.jl. When I changed the topographical error of compexlVector to complexVecor, another sets of error is now being triggered: "ERROR: LoadError: HELICS.Utils.HELICS_ERROR_EXTERNAL_TYPE("`helicsInputGetComplexVector`

### PR DESCRIPTION
**Pull request by josephmckinsey**
I updated the Manifest.toml, since it was testing against HELICS 2.7. We should probably remove the Manifest.toml since most Julia libraries do not have one and instead use better version dependencies like in #30.

Fixes #32.

I also discovered a couple other bugs in that function. One bug involved trying to iterate from 1 to a floating point number, which fails. Another bug involved it casting to a Vector{Float64}.

I may have run a mild formatter on a couple files, which should only change whitespace from what I saw.

### CODE REVIEW

File: src/api.jl [hunk 1]
```diff
@@ -2421,16 +2421,16 @@ Get a complex vector from a [`Subscription`](@ref)
...
+function helicsInputGetComplexVector(ipt::Input)::Vector{ComplexF64}
     maxlen = Cint(helicsInputGetVectorSize(ipt))
     data = Vector{Float64}(undef, maxlen)
     actualSize = Ref(maxlen)
     @invoke_and_check Lib.helicsInputGetComplexVector(ipt, data, maxlen, actualSize)
-	complexVector = Vector{ComplexF64}(undef,0)
-	for i in 1:actualSize[]/2
-		push!(complexVector, data[2*i - 1] + im * data[2*i])
-	end
-    return compelxVector
```
Comment (josephmckinsey) [inline src/api.jl:2433]: For future notice, this is where the main problem is. The rest is mostly just changing tabs to spaces.

**Review by nightlark — APPROVED** [review]
